name = "GraphANN"
uuid = "38438e65-754f-449b-9041-06b96401f6e7"
authors = ["Mark Hildebrand <mhildebrand@ucdavis.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
